export const ADD_CART = 'ADD_CART'
export const REDUCE_CART = 'REDUCE_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const SELECT_DISTYPE= 'SELECT_DISTYPE'
export const INIT_BUYCART = 'INIT_BUYCART'
